# -*- coding: utf-8 -*-
"""numerical_validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1soGI31wwDGU5GolaSSJWq6EbjjghDlYD
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import matplotlib.patches as patches
import matplotlib # <--- ¡ESTO FALTABA!
from IPython.display import HTML

def verify_and_animate():
    print(" Iniciando Auditoría Numérica (Verdad vs. PINN)...")

    # --- 1. CONFIGURACIÓN ---
    L_buffer = 0.8
    Nz = 200
    Nt = 2000

    L_0 = 0.0
    L_f = config.L

    z_grid_phys = np.linspace(L_0, L_f, Nz)
    t_grid = np.linspace(0, config.T_max, Nt)
    dz = z_grid_phys[1] - z_grid_phys[0]
    dt = t_grid[1] - t_grid[0]

    # Grillas visuales
    z_left = np.linspace(L_0 - L_buffer, L_0, 50)
    z_right = np.linspace(L_f, L_f + L_buffer, 50)

    d, gamma = config.d, config.gamma

    # OBTENER EL CONTROL DE LA PINN
    t_tensor = torch.tensor(t_grid, dtype=torch.float32).view(-1, 1).to(device)
    with torch.no_grad():
        omega_vals = net_control(t_tensor).cpu().numpy().flatten()

    # --- 2. SIMULACIÓN NUMÉRICA ---
    P = np.zeros(Nz, dtype=np.complex128)
    S = np.zeros(Nz, dtype=np.complex128)
    E = np.zeros(Nz, dtype=np.complex128)

    E_exit_history = np.zeros(Nt, dtype=np.complex128)
    snapshots = []

    def input_pulse_fn(t_val):
        return config.amplitude * np.exp(-((t_val - config.t_center) / config.width)**2)

    input_intensity_history = np.abs(input_pulse_fn(t_grid))**2

    print("Calculando dinámica de fluidos cuánticos...", end="")

    for i in range(Nt):
        t_curr = t_grid[i]
        Omega = omega_vals[i]

        # A. Inyectar Entrada
        E[0] = input_pulse_fn(t_curr)

        # B. Resolver Ecuaciones
        integral_P = np.cumsum(P) * dz
        E = E[0] + 1j * np.sqrt(d) * integral_P

        dP_dt = -gamma * P + 1j * np.sqrt(d) * E + 1j * Omega * S
        dS_dt = 1j * Omega * P

        P = P + dP_dt * dt
        S = S + dS_dt * dt

        # C. Guardar Salida
        E_exit_history[i] = E[-1]

        # D. Guardar frames
        if i % 20 == 0:
            E_viz_left = input_pulse_fn(t_curr - z_left)

            delay_indices = ((z_right - L_f) / dt).astype(int)
            hist_indices = i - delay_indices
            valid_mask = hist_indices >= 0
            E_viz_right = np.zeros_like(z_right, dtype=np.float64)
            if np.any(valid_mask):
                valid_indices = hist_indices[valid_mask]
                E_viz_right[valid_mask] = np.abs(E_exit_history[valid_indices])**2

            snapshots.append({
                't': t_curr,
                'z_left': z_left, 'E_left': E_viz_left**2,
                'z_phys': z_grid_phys, 'E_phys': np.abs(E)**2, 'S_phys': np.abs(S)**2,
                'z_right': z_right, 'E_right': E_viz_right,
                'Omega': Omega
            })

    print(" ¡Listo!")

    # --- 3. AUDITORÍA ---
    output_intensity_history = np.abs(E_exit_history)**2
    energy_in = np.trapz(input_intensity_history, t_grid)
    energy_out = np.trapz(output_intensity_history, t_grid)
    real_efficiency = (energy_out / energy_in) * 100
    theory_limit = (1 - 2.9/d) * 100

    print(f"\n📊 === REPORTE DE VERDAD (SIMULACIÓN NUMÉRICA) ===")
    print(f"Eficiencia REAL:     {real_efficiency:.2f}%")
    print(f"Límite Teórico:      {theory_limit:.2f}%")
    print(f"Diferencia con PINN: {94.28 - real_efficiency:.2f}%")

    # Gráfica Estática
    plt.figure(figsize=(10, 5))
    plt.plot(t_grid, input_intensity_history, 'g--', label='Input (Entrada)', alpha=0.6)
    plt.plot(t_grid, output_intensity_history, 'r-', label='Output Real (Salida)', linewidth=2)
    plt.fill_between(t_grid, output_intensity_history, color='red', alpha=0.1)
    plt.title(f"Resultado Real: {real_efficiency:.1f}% Eficiencia")
    plt.xlabel("Tiempo")
    plt.legend()
    plt.grid(True)
    plt.show()

    # --- 4. ANIMACIÓN ---
    print("Generando animación...")
    fig, (ax_lab, ax_ctrl) = plt.subplots(2, 1, figsize=(12, 8), gridspec_kw={'height_ratios': [2, 1]})
    plt.close()

    medium_box = patches.Rectangle((L_0, -0.1), L_f - L_0, 1.5, linewidth=2, edgecolor='#555', facecolor='#f0f0f0', zorder=0)
    ax_lab.add_patch(medium_box)

    ax_lab.text(L_0 - L_buffer/2, 1.3, "VACÍO (In)", ha='center', color='green', fontsize=9)
    ax_lab.text(L_f + L_buffer/2, 1.3, "VACÍO (Out)", ha='center', color='red', fontsize=9)
    ax_lab.text((L_0 + L_f)/2, 1.3, f"[ MEDIO ATÓMICO ]", ha='center', fontweight='bold', color='#333')

    line_E_left, = ax_lab.plot([], [], 'g-', linewidth=2, alpha=0.6)
    line_E_mid, = ax_lab.plot([], [], 'b-', linewidth=3, label=r'Luz ($|\mathcal{E}|^2$)')
    line_E_right, = ax_lab.plot([], [], 'r-', linewidth=2)
    line_S, = ax_lab.plot([], [], 'm-', linewidth=3, label=r'Memoria ($|S|^2$)')

    ax_lab.set_xlim(L_0 - L_buffer, L_f + L_buffer)
    ax_lab.set_ylim(-0.1, 1.5)
    ax_lab.axvline(L_0, color='k', linestyle=':', alpha=0.3)
    ax_lab.axvline(L_f, color='k', linestyle=':', alpha=0.3)

    ax_ctrl.plot(t_grid, omega_vals, 'k--', alpha=0.3)
    dot_ctrl, = ax_ctrl.plot([], [], 'ro', markersize=10)
    line_trace, = ax_ctrl.plot([], [], 'r-', linewidth=2)
    ax_ctrl.set_xlim(0, config.T_max)
    ax_ctrl.set_ylim(0, max(omega_vals)*1.1)
    ax_ctrl.grid(True)

    def update(frame_idx):
        data = snapshots[frame_idx]
        line_E_left.set_data(data['z_left'], data['E_left'])
        line_E_mid.set_data(data['z_phys'], data['E_phys'])
        line_S.set_data(data['z_phys'], data['S_phys'])

        # Limpieza robusta de colecciones (polígonos de relleno)
        for collection in list(ax_lab.collections):
             if isinstance(collection, matplotlib.collections.PolyCollection):
                 collection.remove()

        ax_lab.add_patch(medium_box)
        ax_lab.fill_between(data['z_phys'], data['S_phys'], color='magenta', alpha=0.3)

        line_E_right.set_data(data['z_right'], data['E_right'])
        ax_lab.set_title(f"Tiempo: {data['t']:.2f} s", fontsize=14)
        dot_ctrl.set_data([data['t']], [data['Omega']])
        current_idx = np.searchsorted(t_grid, data['t'])
        line_trace.set_data(t_grid[:current_idx], omega_vals[:current_idx])
        return line_E_mid, line_S

    ani = animation.FuncAnimation(fig, update, frames=len(snapshots), interval=40)
    ani.save("auditoria_final.gif", writer='pillow', fps=25)
    return HTML(ani.to_jshtml())

verify_and_animate()