# -*- coding: utf-8 -*-
"""pinn_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SfBTS5Zf0ujrGlq4BuMIxPwzw6Alezn2
"""

import os
# Esta línea mágica permite que existan dos copias de la librería sin chocar
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output

# Configurar dispositivo
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"🚀 Usando dispositivo: {device}")

# ==========================================
# 1. CONFIGURACIÓN FÍSICA
# ==========================================
class PhysicsConfig:
    def __init__(self):
        self.d = 30.0       # Profundidad Óptica
        self.gamma = 0.0    # Decaimiento
        self.delta = 0.0    # Resonancia
        self.L = 1.0
        self.T_max = 10.0
        self.t_center = 2.0
        self.width = 0.5
        self.amplitude = 1.0

    def input_pulse_func(self, t):
        return self.amplitude * torch.exp(-((t - self.t_center) / self.width)**2)

    def target_output_func(self, t):
        t_reversed = self.T_max - t
        return self.input_pulse_func(t_reversed)

config = PhysicsConfig()

# ==========================================
# 2. REDES NEURONALES
# ==========================================
class Net_Fields(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(2, 64), nn.Tanh(),
            nn.Linear(64, 64), nn.Tanh(),
            nn.Linear(64, 64), nn.Tanh(),
            nn.Linear(64, 64), nn.Tanh(),
            nn.Linear(64, 6)
        )
    def forward(self, z, t):
        cat_input = torch.cat([z, t], dim=1)
        out = self.net(cat_input)
        return out[:,0:1], out[:,1:2], out[:,2:3], out[:,3:4], out[:,4:5], out[:,5:6]

class Net_Control(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(1, 64), nn.Tanh(),
            nn.Linear(64, 64), nn.Tanh(),
            nn.Linear(64, 64), nn.Tanh(),
            nn.Linear(64, 1),
            nn.Softplus() # Omega siempre positivo
        )
    def forward(self, t):
        return self.net(t)

net_fields = Net_Fields().to(device)
net_control = Net_Control().to(device)

# ==========================================
# 3. FÍSICA Y GENERADOR
# ==========================================
def physics_loss(model_fields, model_control, z, t, config):
    # Predicciones
    E_r, E_i, P_r, P_i, S_r, S_i = model_fields(z, t)
    Omega = model_control(t)

    # Derivadas (create_graph=True)
    dEr_dz = torch.autograd.grad(E_r, z, torch.ones_like(E_r), create_graph=True)[0]
    dEi_dz = torch.autograd.grad(E_i, z, torch.ones_like(E_i), create_graph=True)[0]
    dPr_dt = torch.autograd.grad(P_r, t, torch.ones_like(P_r), create_graph=True)[0]
    dPi_dt = torch.autograd.grad(P_i, t, torch.ones_like(P_i), create_graph=True)[0]
    dSr_dt = torch.autograd.grad(S_r, t, torch.ones_like(S_r), create_graph=True)[0]
    dSi_dt = torch.autograd.grad(S_i, t, torch.ones_like(S_i), create_graph=True)[0]

    # Ecuaciones Gorshkov
    d = config.d
    res_E_real = dEr_dz + np.sqrt(d) * P_i
    res_E_imag = dEi_dz - np.sqrt(d) * P_r
    res_P_real = dPr_dt - (-P_r - np.sqrt(d)*E_i - Omega*S_i) # delta=0 simplificado
    res_P_imag = dPi_dt - (-P_i + np.sqrt(d)*E_r + Omega*S_r)
    res_S_real = dSr_dt - (-Omega * P_i)
    res_S_imag = dSi_dt - ( Omega * P_r)

    return (torch.mean(res_E_real**2) + torch.mean(res_E_imag**2) +
            torch.mean(res_P_real**2) + torch.mean(res_P_imag**2) +
            torch.mean(res_S_real**2) + torch.mean(res_S_imag**2))

def get_batch(config, batch_size=262144):
    z_col = (torch.rand(batch_size, 1, device=device) * config.L).requires_grad_(True)
    t_col = (torch.rand(batch_size, 1, device=device) * config.T_max).requires_grad_(True)

    z_bc = torch.zeros(batch_size // 2, 1, device=device)
    t_bc = torch.rand(batch_size // 2, 1, device=device) * config.T_max

    z_ic = torch.rand(batch_size // 4, 1, device=device) * config.L
    t_ic = torch.zeros(batch_size // 4, 1, device=device)

    z_target = torch.ones(batch_size // 2, 1, device=device) * config.L
    t_target = torch.rand(batch_size // 2, 1, device=device) * config.T_max

    return z_col, t_col, z_bc, t_bc, z_ic, t_ic, z_target, t_target

# ==========================================
# 4. ENTRENAMIENTO DINÁMICO
# ==========================================
optimizer = optim.Adam(
    list(net_fields.parameters()) + list(net_control.parameters()),
    lr=0.001
)
loss_history = []

def plot_results(epoch, w_phy, w_bc, w_target):
    clear_output(wait=True)
    t_test = torch.linspace(0, config.T_max, 200).view(-1, 1).to(device)
    z_in = torch.zeros_like(t_test)
    z_out = torch.ones_like(t_test) * config.L

    with torch.no_grad():
        omega_pred = net_control(t_test)
        E_in_r, _, _, _, _, _ = net_fields(z_in, t_test)
        E_out_r, _, _, _, _, _ = net_fields(z_out, t_test)

    t_np = t_test.cpu().numpy()
    target_out_np = config.target_output_func(t_test).cpu().numpy()

    fig, ax = plt.subplots(1, 3, figsize=(18, 5))
    ax[0].plot(loss_history)
    ax[0].set_yscale('log')
    ax[0].set_title(f"Loss (Ep {epoch}) | W_Phy={w_phy:.1f}, W_Tgt={w_target:.1f}")
    ax[0].grid(True)

    ax[1].plot(t_np, E_in_r.cpu().numpy(), 'g--', label="Input Real (Red)")
    ax[1].plot(t_np, config.input_pulse_func(t_test).cpu().numpy(), 'g:', alpha=0.3, label="Input Ideal")
    ax[1].plot(t_np, target_out_np, 'k:', alpha=0.5, label="Target Ideal")
    ax[1].plot(t_np, E_out_r.cpu().numpy(), 'b-', linewidth=2, label="Output (Red)")
    ax[1].set_title("Propagación (Entrada vs Salida)")
    ax[1].legend()
    ax[1].grid(True)

    ax[2].plot(t_np, omega_pred.cpu().numpy(), 'r-', linewidth=2)
    ax[2].set_title(r"Control $\Omega(t)$")
    ax[2].grid(True)
    plt.show()

def train_dynamic(epochs=7000):
    print("🧠 Iniciando Entrenamiento por Currículo...")
    for epoch in range(epochs):
        w_bc = 100.0
        w_ic = 10.0

        if epoch < 1000:
            w_phy = 10.0; w_target = 1.0; phase = "Fase 1: Física Básica"
        elif epoch < 3000:
            progress = (epoch - 1000) / 2000
            w_phy = 10.0; w_target = 1.0 + 19.0 * progress; phase = "Fase 2: Transición"
        else:
            w_phy = 10.0; w_target = 20.0 + 30.0 * ((epoch - 3000) / 3000); phase = "Fase 3: Optimización Fina"

        optimizer.zero_grad()
        z_col, t_col, z_bc, t_bc, z_ic, t_ic, z_target, t_target = get_batch(config)
        loss_phy = physics_loss(net_fields, net_control, z_col, t_col, config)
        E_r_bc, E_i_bc, _, _, _, _ = net_fields(z_bc, t_bc)
        loss_bc = torch.mean((E_r_bc - config.input_pulse_func(t_bc))**2) + torch.mean(E_i_bc**2)
        _, _, P_r_ic, P_i_ic, S_r_ic, S_i_ic = net_fields(z_ic, t_ic)
        loss_ic = torch.mean(P_r_ic**2 + P_i_ic**2 + S_r_ic**2 + S_i_ic**2)
        E_r_out, E_i_out, _, _, _, _ = net_fields(z_target, t_target)
        loss_target = torch.mean((E_r_out - config.target_output_func(t_target))**2) + torch.mean(E_i_out**2)
        total_loss = w_phy*loss_phy + w_bc*loss_bc + w_ic*loss_ic + w_target*loss_target
        total_loss.backward()
        optimizer.step()
        loss_history.append(total_loss.item())

        if epoch % 200 == 0:
            print(f"Epoch {epoch} | {phase} | Target Weight: {w_target:.2f}")
            plot_results(epoch, w_phy, w_bc, w_target)

train_dynamic(epochs=6001)

def calculate_efficiency():
    t_vals = torch.linspace(0, config.T_max, 1000).view(-1, 1).to(device)
    z_out = torch.ones_like(t_vals) * config.L
    with torch.no_grad():
        E_r_out, E_i_out, _, _, _, _ = net_fields(z_out, t_vals)
        E_out_mag2 = (E_r_out**2 + E_i_out**2).cpu().numpy().flatten()
        E_in_mag2 = (config.input_pulse_func(t_vals)**2).cpu().numpy().flatten()
    t_np = t_vals.cpu().numpy().flatten()
    energy_in = np.trapz(E_in_mag2, t_np)
    energy_out = np.trapz(E_out_mag2, t_np)
    efficiency = (energy_out / energy_in) * 100
    limit = (1 - 2.9/config.d) * 100
    print(f"\n=== RESULTADOS FINALES ===")
    print(f"Eficiencia Lograda: {efficiency:.2f}%")
    print(f"Límite Teórico (d={config.d}): {limit:.2f}%")
calculate_efficiency()